package cl.duoc.innovacion.smartshopp.persistence;
// Generated 06-05-2017 15:37:59 by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Oferta generated by hbm2java
 */
@Entity
public class Oferta implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	private int idOferta;
	private Integer idTienda;
	private Integer idCategoria;
	private Date fechaPublicacion;
	private Character destacada;

	public Oferta() {
	}

	public Oferta(int idOferta) {
		this.idOferta = idOferta;
	}

	public Oferta(int idOferta, Integer idTienda, Integer idCategoria, Date fechaPublicacion, Character destacada) {
		this.idOferta = idOferta;
		this.idTienda = idTienda;
		this.idCategoria = idCategoria;
		this.fechaPublicacion = fechaPublicacion;
		this.destacada = destacada;
	}

	public int getIdOferta() {
		return this.idOferta;
	}

	public void setIdOferta(int idOferta) {
		this.idOferta = idOferta;
	}

	public Integer getIdTienda() {
		return this.idTienda;
	}

	public void setIdTienda(Integer idTienda) {
		this.idTienda = idTienda;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public Character getDestacada() {
		return this.destacada;
	}

	public void setDestacada(Character destacada) {
		this.destacada = destacada;
	}

}
