package cl.duoc.innovacion.smartshopp.persistence;
// Generated 06-05-2017 15:37:59 by Hibernate Tools 5.2.1.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Pago generated by hbm2java
 */
@Entity
public class Pago implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	private int idPago;
	private Integer idCupon;
	private String tipo;
	private Character estado;

	public Pago() {
	}

	public Pago(int idPago) {
		this.idPago = idPago;
	}

	public Pago(int idPago, Integer idCupon, String tipo, Character estado) {
		this.idPago = idPago;
		this.idCupon = idCupon;
		this.tipo = tipo;
		this.estado = estado;
	}

	public int getIdPago() {
		return this.idPago;
	}

	public void setIdPago(int idPago) {
		this.idPago = idPago;
	}

	public Integer getIdCupon() {
		return this.idCupon;
	}

	public void setIdCupon(Integer idCupon) {
		this.idCupon = idCupon;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
