package cl.duoc.innovacion.smartshopp.persistence;
// Generated 06-05-2017 15:37:59 by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Producto generated by hbm2java
 */
@Entity
public class Producto implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	private int idProducto;
	private Integer idCategoria;
	private String nombre;
	private Integer valor;
	private Integer stock;
	private Integer tamano;
	private String color;
	private String peso;
	private String talla;
	private Character descontinuado;
	private Date ultimaActualizacion;

	public Producto() {
	}

	public Producto(int idProducto) {
		this.idProducto = idProducto;
	}

	public Producto(int idProducto, Integer idCategoria, String nombre, Integer valor, Integer stock, Integer tamano,
			String color, String peso, String talla, Character descontinuado, Date ultimaActualizacion) {
		this.idProducto = idProducto;
		this.idCategoria = idCategoria;
		this.nombre = nombre;
		this.valor = valor;
		this.stock = stock;
		this.tamano = tamano;
		this.color = color;
		this.peso = peso;
		this.talla = talla;
		this.descontinuado = descontinuado;
		this.ultimaActualizacion = ultimaActualizacion;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Integer getTamano() {
		return this.tamano;
	}

	public void setTamano(Integer tamano) {
		this.tamano = tamano;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getPeso() {
		return this.peso;
	}

	public void setPeso(String peso) {
		this.peso = peso;
	}

	public String getTalla() {
		return this.talla;
	}

	public void setTalla(String talla) {
		this.talla = talla;
	}

	public Character getDescontinuado() {
		return this.descontinuado;
	}

	public void setDescontinuado(Character descontinuado) {
		this.descontinuado = descontinuado;
	}

	public Date getUltimaActualizacion() {
		return this.ultimaActualizacion;
	}

	public void setUltimaActualizacion(Date ultimaActualizacion) {
		this.ultimaActualizacion = ultimaActualizacion;
	}

}
