package cl.duoc.innovacion.smartshopp.persistence;
// Generated 06-05-2017 15:37:59 by Hibernate Tools 5.2.1.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Tienda generated by hbm2java
 */
@Entity
public class Tienda implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	private int idTienda;
	private String nombre;
	private Integer idDireccion;
	private Character publicar;

	public Tienda() {
	}

	public Tienda(int idTienda) {
		this.idTienda = idTienda;
	}

	public Tienda(int idTienda, String nombre, Integer idDireccion, Character publicar) {
		this.idTienda = idTienda;
		this.nombre = nombre;
		this.idDireccion = idDireccion;
		this.publicar = publicar;
	}

	public int getIdTienda() {
		return this.idTienda;
	}

	public void setIdTienda(int idTienda) {
		this.idTienda = idTienda;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	public Character getPublicar() {
		return this.publicar;
	}

	public void setPublicar(Character publicar) {
		this.publicar = publicar;
	}

}
