package cl.duoc.innovacion.smartshopp.persistence;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated 06-05-2017 15:37:59 by Hibernate Tools 5.2.1.Final

/**
 * Usuario generated by hbm2java
 */
@Entity
public class Usuario implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	private int idUsuario;
	private String rut;
	private Character esCliente;

	public Usuario() {
	}

	public Usuario(int idUsuario, String rut) {
		this.idUsuario = idUsuario;
		this.rut = rut;
	}

	public Usuario(int idUsuario, String rut, Character esCliente) {
		this.idUsuario = idUsuario;
		this.rut = rut;
		this.esCliente = esCliente;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	public Character getEsCliente() {
		return this.esCliente;
	}

	public void setEsCliente(Character esCliente) {
		this.esCliente = esCliente;
	}

}
