package cl.duoc.innovacion.smartshopp.persistence;
// Generated 06-05-2017 15:37:59 by Hibernate Tools 5.2.1.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Venta generated by hbm2java
 */
@Entity
public class Venta implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	private int idVenta;
	private Integer idPago;
	private Integer descuento;
	private Integer cantidad;

	public Venta() {
	}

	public Venta(int idVenta) {
		this.idVenta = idVenta;
	}

	public Venta(int idVenta, Integer idPago, Integer descuento, Integer cantidad) {
		this.idVenta = idVenta;
		this.idPago = idPago;
		this.descuento = descuento;
		this.cantidad = cantidad;
	}

	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	public Integer getIdPago() {
		return this.idPago;
	}

	public void setIdPago(Integer idPago) {
		this.idPago = idPago;
	}

	public Integer getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Integer descuento) {
		this.descuento = descuento;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
